export const full_blocks = [

  ["brown_ceramic.png",
  "brown_concrete.png",
  "brown_glazed_ceramic.png",
  "brown_polished_ceramic.png",
  "brown_sheet_metal.png",
  "brown_terracotta_tiles.png",
  "mud.png",],

["black_ceramic.png",
"black_concrete.png",
"black_glazed_ceramic.png",
"black_polished_ceramic.png",
"black_sheet_metal.png",
"black_terracotta_tiles.png",
"charred_planks.png",],

["gray_ceramic.png",
"gray_concrete.png",
"gray_glazed_ceramic.png",
"gray_polished_ceramic.png",
"gray_sheet_metal.png",
"gray_terracotta_tiles.png"],

["light_gray_ceramic.png",
"light_gray_concrete.png",
"light_gray_glazed_ceramic.png",
"light_gray_polished_ceramic.png",
"light_gray_sheet_metal.png",
"light_gray_terracotta_tiles.png",
"weathered_planks.png",],


["cyan_ceramic.png",
"cyan_concrete.png",
"cyan_glazed_ceramic.png",
"cyan_polished_ceramic.png",
"cyan_sheet_metal.png",
"cyan_terracotta_tiles.png"],

["red_ceramic.png",
"red_concrete.png",
"red_glazed_ceramic.png",
"red_polished_ceramic.png",
"red_sheet_metal.png",
"red_terracotta_tiles.png"],

["orange_ceramic.png",
"orange_concrete.png",
"orange_glazed_ceramic.png",
"orange_polished_ceramic.png",
"orange_sheet_metal.png",
"orange_terracotta_tiles.png"],

["yellow_ceramic.png",
"yellow_concrete.png",
"yellow_glazed_ceramic.png",
"yellow_polished_ceramic.png",
"yellow_sheet_metal.png",
"yellow_terracotta_tiles.png",
"cut_gold_block.png",],

["lime_ceramic.png",
"lime_concrete.png",
"lime_glazed_ceramic.png",
"lime_polished_ceramic.png",
"lime_sand_bricks.png",
"lime_sheet_metal.png",
"lime_terracotta_tiles.png",],

["green_ceramic.png",
"green_concrete.png",
"green_glazed_ceramic.png",
"green_polished_ceramic.png",
"green_sheet_metal.png",
"green_terracotta_tiles.png"],

["light_blue_ceramic.png",
"light_blue_concrete.png",
"light_blue_glazed_ceramic.png",
"light_blue_polished_ceramic.png",
"light_blue_sheet_metal.png",
"light_blue_terracotta_tiles.png",
"concrete.png",],

["blue_ceramic.png",
"blue_concrete.png",
"blue_glazed_ceramic.png",
"blue_polished_ceramic.png",
"blue_sheet_metal.png",
"blue_terracotta_tiles.png",
"slate.png",],

["purple_ceramic.png",
"purple_concrete.png",
"purple_glazed_ceramic.png",
"purple_polished_ceramic.png",
"purple_sheet_metal.png",
"purple_terracotta_tiles.png"],

["magenta_ceramic.png",
"magenta_concrete.png",
"magenta_glazed_ceramic.png",
"magenta_polished_ceramic.png",
"magenta_sheet_metal.png",
"magenta_terracotta_tiles.png",],

["pink_ceramic.png",
"pink_concrete.png",
"pink_glazed_ceramic.png",
"pink_polished_ceramic.png",
"pink_sheet_metal.png",
"pink_terracotta_tiles.png"],

["beige_ceramic.png",
"beige_concrete.png",
"beige_glazed_ceramic.png",
"beige_polished_ceramic.png",
"beige_sheet_metal.png",
"beige_terracotta_tiles.png",
"adobe_bricks.png",
"raw_concrete.png"],


["white_ceramic.png",
"white_concrete.png",
"white_glazed_ceramic.png",
"white_polished_ceramic.png",
"white_sheet_metal.png",
"white_terracotta_tiles.png",
"marble.png",
"cut_iron_block.png"],

["cut_limestone_bricks.png",
"cut_limestone.png",
"cut_weathered_limestone_bricks.png",
"cut_weathered_limestone.png",
"limestone_bricks.png",
"limestone.png",
"weathered_limestone_bricks.png",
"weathered_limestone.png",],


]
